```{r echo=FALSE}
yml_content <- yaml::read_yaml("chapterauthors.yml")
author <- yml_content[["lab3shortname"]][["author"]]
```
# Lab Title {#lab-short-name}

Written by
```{r results='asis', echo=FALSE}
cat(author)
```

## Lab Overview {-}

Lorem ipsum

------------------------------------------------------------------------

## Learning Objectives {-}

-   Lorem ipsum

-   Lorem ipsum 

-   Lorem ipsum 

------------------------------------------------------------------------

## Competencies in This Lab {-}

-   Lorem ipsum

-   Lorem ipsum

-   Lorem ipsum

------------------------------------------------------------------------

## Deliverables {-}

-   Lorem ipsum

-   Lorem ipsum

-   Lorem ipsum

------------------------------------------------------------------------

## Data {-}

Lorem ipsum

------------------------------------------------------------------------

## Task 1: Lorem ipsum {-}

Lorem ipsum

**Step 1:** Lorem ipsum.

**Step 2:** Lorem ipsum.

**Step 3:** Lorem ipsum.

__HINT: Lorem ipsum.__

##### Q1. LOREM IPSUM? {-}

##### Q2. LOREM IPSUM? {-}

------------------------------------------------------------------------

## Task 2: Lorem ipsum {-}

Lorem ipsum

**Step 1:** Lorem ipsum.

**Step 2:** Lorem ipsum.

**Step 3:** Lorem ipsum.

__HINT: Lorem ipsum.__

##### Q3. LOREM IPSUM? {-}

##### Q4. LOREM IPSUM? {-}